/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Communication.DataManager;
import Communication.Engine;
import static Communication.Engine.GetMarcaModelo;
import static Communication.Engine.GetRowSize;
import static Communication.Engine.GetSingleData;
import static Communication.Engine.MarcaModeloCBox;
import static Communication.Engine.ProductToTable;
import static Communication.Engine.RowToComboBox;
import Communication.LabelTimer;
import javax.swing.JOptionPane;

/**
 *
 * @author LeoFuking
 */
public class ForProd extends javax.swing.JPanel {

    private boolean echo = false;
    
    private int Marca = 0;
    private int Modelo = 0;
    private int Pintura = 0;
    private String Cor = "";
    
    public ForProd() {
        initComponents();
        salvo.setVisible(false);
        ResetFrame();
        modelo.setModel(Engine.RowToComboBox("modelo", "nome"));
        pintura.setModel(Engine.RowToComboBox("pintura", "nome"));
        marca.setModel(Engine.RowToComboBox("marca", "nome"));
        fornecedor.setModel(Engine.RowToComboBox("fornecedor","nome"));
    }
    
    private void ResetFrame(){
        cor.setText("");
        modelo.setSelectedIndex(0);
        pintura.setSelectedIndex(0);
        marca.setSelectedIndex(0);
        tabela.setModel(ProductToTable(0,0,"",0));
        fornecedor.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salvar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        marca = new javax.swing.JComboBox<>();
        pintura = new javax.swing.JComboBox<>();
        modelo = new javax.swing.JComboBox<>();
        fornecedor = new javax.swing.JComboBox<>();
        cor = new javax.swing.JTextField();
        salvo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fornecedor-Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 0, 14))); // NOI18N

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        jLabel1.setText("Cor");
        jLabel1.setPreferredSize(new java.awt.Dimension(17, 29));

        jLabel3.setText("Fornecedor");

        jLabel2.setText("Marca");

        jLabel5.setText("Modelo");

        jLabel6.setText("Pintura");
        jLabel6.setPreferredSize(new java.awt.Dimension(34, 29));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        marca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                marcaItemStateChanged(evt);
            }
        });
        marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                marcaMousePressed(evt);
            }
        });

        pintura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pintura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pinturaItemStateChanged(evt);
            }
        });

        modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modeloItemStateChanged(evt);
            }
        });
        modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modeloMousePressed(evt);
            }
        });

        fornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fornecedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fornecedorItemStateChanged(evt);
            }
        });

        cor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                corKeyReleased(evt);
            }
        });

        salvo.setForeground(new java.awt.Color(51, 204, 0));
        salvo.setText("Salvo com sucesso!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marca, 0, 212, Short.MAX_VALUE)
                            .addComponent(cor))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pintura, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salvo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pintura, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limpar)
                            .addComponent(salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salvo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
 if(tabela.getSelectedRowCount() == 0){JOptionPane.showMessageDialog(null,"Selecione no mínimo uma linha na tabela para salvar");}
        else{
            if(fornecedor.getSelectedItem() == ""){JOptionPane.showMessageDialog(null,"Selecione um fornecedor");}
            else{
                boolean done = true;
                String[] save = new String[2];
                save[1] = (String) GetSingleData("SELECT nome FROM fornecedor WHERE nome LIKE '"+fornecedor.getSelectedItem()+"'","nome");
                int[] Rows = tabela.getSelectedRows();
                for(int i = 0; i < Rows.length; i++){
                    if(tabela.getValueAt(Rows[i],4) == null){JOptionPane.showMessageDialog(null,"Produto na linha "+(Rows[i]+1)+" é inválido");done = false;}
                    else{
                        save[0] = String.valueOf(tabela.getValueAt(Rows[i],4));
                        int s1 = GetRowSize("for_prod");
                        DataManager.CadastrarFor_prod(save);
                        int s2 = GetRowSize("for_prod");
                        if(s2 > s1){salvo.setVisible(true);new LabelTimer(2,salvo);}
                    }
                    if(done == true){
                        ResetFrame();
                    }
                }
            }
        }
    }//GEN-LAST:event_salvarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        ResetFrame();
    }//GEN-LAST:event_limparActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked

    }//GEN-LAST:event_tabelaMouseClicked

    private void tabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseReleased
        
    }//GEN-LAST:event_tabelaMouseReleased

    private void marcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_marcaItemStateChanged
                if(echo) echo = false;
        else{
            echo = true;
            if(marca.getSelectedItem() == ""){
                modelo.setModel(RowToComboBox("modelo", "nome"));
                Marca = 0;
                Modelo = 0;
                tabela.setModel(ProductToTable(Marca,Modelo,Cor,Pintura));
            }else{
                Marca = (int) GetSingleData("SELECT marca_id FROM marca WHERE nome LIKE '"+marca.getSelectedItem()+"'","marca_id");
                tabela.setModel(ProductToTable(Marca,Modelo,Cor,Pintura));
                modelo.setModel(MarcaModeloCBox(true,String.valueOf(Marca)));
            }
        }
    }//GEN-LAST:event_marcaItemStateChanged

    private void pinturaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pinturaItemStateChanged
        if(pintura.getSelectedItem() == ""){
            Pintura = 0;
            tabela.setModel(ProductToTable(Marca,Modelo,Cor,Pintura));
        }else{
            Pintura = (int) GetSingleData("SELECT pintura_id FROM pintura WHERE nome LIKE '"+pintura.getSelectedItem()+"'","pintura_id");
            tabela.setModel(ProductToTable(Marca,Modelo,Cor,Pintura));
        }
    }//GEN-LAST:event_pinturaItemStateChanged

    private void modeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modeloItemStateChanged
    if(echo) echo = false;
    else{
        echo = true;
        if(modelo.getSelectedItem() == ""){
            marca.setModel(RowToComboBox("marca", "nome"));
            Modelo = 0;
            tabela.setModel(ProductToTable(Marca,Modelo,Cor,Pintura));
        }else{
            Modelo = (int) GetSingleData("SELECT modelo_id FROM modelo WHERE nome LIKE '"+modelo.getSelectedItem()+"'","modelo_id");
            tabela.setModel(ProductToTable(Marca,Modelo,Cor,Pintura));
            String buffer = String.valueOf(modelo.getSelectedItem());
            String[] s = new String[1];
            s = GetMarcaModelo(false,String.valueOf(modelo.getSelectedItem()));
            marca.setSelectedItem(s[0]);
            modelo.setSelectedItem(buffer);
        }
    }
    }//GEN-LAST:event_modeloItemStateChanged

    private void fornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fornecedorItemStateChanged
        
    }//GEN-LAST:event_fornecedorItemStateChanged

    private void corKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corKeyReleased
    if(cor.getText() != null){
            Cor = cor.getText();
            tabela.setModel(ProductToTable(Marca,Modelo,Cor,Pintura));
        }
    }//GEN-LAST:event_corKeyReleased

    private void marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaMousePressed
        echo = false;
    }//GEN-LAST:event_marcaMousePressed

    private void modeloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeloMousePressed
        echo = false;
    }//GEN-LAST:event_modeloMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cor;
    private javax.swing.JComboBox<String> fornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpar;
    private javax.swing.JComboBox<String> marca;
    private javax.swing.JComboBox<String> modelo;
    private javax.swing.JComboBox<String> pintura;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel salvo;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
