/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Communication.Engine.GetSingleData;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author LeoFuking
 */
public class MainFrame extends javax.swing.JFrame {
    CardLayout c;
    int[] funcionario = new int[2];

    public int getPermissao() {
       return funcionario[0];
    }
    
    public MainFrame(int[] s) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();
        
        c = (CardLayout) MainPanel.getLayout();
        funcionario = s;
        addhome();
        addforprod();
        addvenda();
        addvendedor();
        addfornecedor();
        addcliente();
        addproduto();
        addvisualizar();
        addestoque();
        adddebug();
        addsql();
    }
    
    private void addhome(){Home home = new Home((String) GetSingleData("SELECT nome FROM funcionario WHERE funcionario_id = "+funcionario[1],"nome"));MainPanel.add(home, "home");}
    private void addforprod(){ForProd forprod = new ForProd();MainPanel.add(forprod, "forprod");}
    private void addvenda(){Venda venda = new Venda(this);MainPanel.add(venda, "venda");}
    private void addvendedor(){Funcionario vendedor = new Funcionario(this);MainPanel.add(vendedor, "vendedor");}
    private void addfornecedor(){Fornecedor fornecedor = new Fornecedor();MainPanel.add(fornecedor, "fornecedor");}
    private void addcliente(){Cliente cliente = new Cliente();MainPanel.add(cliente,"cliente");}
    private void addproduto(){Produto produto = new Produto();MainPanel.add(produto,"produto");}
    private void addvisualizar(){Visualizar visualizar = new Visualizar();MainPanel.add(visualizar,"visualizar");}
    private void addestoque(){Estoque estoque = new Estoque(funcionario[0]);MainPanel.add(estoque,"estoque");}
    private void adddebug(){Debug debug = new Debug();MainPanel.add(debug,"debug");}
    private void addsql(){Sql sql = new Sql();MainPanel.add(sql,"sql");}

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        MainPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        venda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cliente = new javax.swing.JMenuItem();
        funcionari = new javax.swing.JMenuItem();
        produto = new javax.swing.JMenuItem();
        fornecedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        forprod = new javax.swing.JMenuItem();
        visualizar = new javax.swing.JMenu();
        estoque = new javax.swing.JMenu();
        avançado = new javax.swing.JMenu();
        debug = new javax.swing.JMenuItem();
        sql = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));

        MainPanel.setPreferredSize(new java.awt.Dimension(1200, 770));
        MainPanel.setLayout(new java.awt.CardLayout());

        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 30));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database/img/logo.png"))); // NOI18N
        home.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        home.setPreferredSize(new java.awt.Dimension(35, 29));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        jMenuBar1.add(home);

        jMenu1.setText("Cadastrar");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(0, 4, 0, 4));

        venda.setText("Venda");
        venda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaActionPerformed(evt);
            }
        });
        jMenu1.add(venda);
        jMenu1.add(jSeparator1);

        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        jMenu1.add(cliente);

        funcionari.setText("Funcionário");
        funcionari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionariActionPerformed(evt);
            }
        });
        jMenu1.add(funcionari);

        produto.setText("Produto");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        jMenu1.add(produto);

        fornecedor.setText("Fornecedor");
        fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(fornecedor);
        jMenu1.add(jSeparator2);

        forprod.setText("Fornecedor-Produto");
        forprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forprodActionPerformed(evt);
            }
        });
        jMenu1.add(forprod);

        jMenuBar1.add(jMenu1);

        visualizar.setText("Visualizar");
        visualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        visualizar.setMargin(new java.awt.Insets(0, 4, 0, 4));
        visualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visualizarMousePressed(evt);
            }
        });
        jMenuBar1.add(visualizar);

        estoque.setText("Estoque");
        estoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estoque.setMargin(new java.awt.Insets(0, 4, 0, 4));
        estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                estoqueMousePressed(evt);
            }
        });
        jMenuBar1.add(estoque);

        avançado.setText("Avançado");
        avançado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avançado.setMargin(new java.awt.Insets(0, 4, 0, 4));

        debug.setText("Debug");
        debug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugActionPerformed(evt);
            }
        });
        avançado.add(debug);

        sql.setText("Enviar comando SQL");
        sql.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqlActionPerformed(evt);
            }
        });
        avançado.add(sql);

        jMenuBar1.add(avançado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaActionPerformed
        c.show(MainPanel, "venda");
    }//GEN-LAST:event_vendaActionPerformed

    private void forprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forprodActionPerformed
        if(funcionario[0] > 1)c.show(MainPanel, "forprod");else JOptionPane.showMessageDialog(null, "Permissão negada");
    }//GEN-LAST:event_forprodActionPerformed

    private void fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorActionPerformed
        if(funcionario[0] > 1)c.show(MainPanel, "fornecedor");else JOptionPane.showMessageDialog(null, "Permissão negada");
    }//GEN-LAST:event_fornecedorActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        if(funcionario[0] > 1)c.show(MainPanel, "produto");else JOptionPane.showMessageDialog(null, "Permissão negada");
    }//GEN-LAST:event_produtoActionPerformed

    private void funcionariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionariActionPerformed
        if(funcionario[0] > 1)c.show(MainPanel, "vendedor");else JOptionPane.showMessageDialog(null, "Permissão negada");
    }//GEN-LAST:event_funcionariActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        c.show(MainPanel, "cliente");
    }//GEN-LAST:event_clienteActionPerformed

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        c.show(MainPanel, "home");
        home.setSelected(false);
    }//GEN-LAST:event_homeMousePressed

    private void visualizarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizarMousePressed
        if(funcionario[0] > 1) c.show(MainPanel, "visualizar");else JOptionPane.showMessageDialog(null, "Permissão negada");
        visualizar.setSelected(false);
    }//GEN-LAST:event_visualizarMousePressed

    private void estoqueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estoqueMousePressed
        c.show(MainPanel, "estoque");
        estoque.setSelected(false);
    }//GEN-LAST:event_estoqueMousePressed

    private void debugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugActionPerformed
        if(funcionario[0] > 2)c.show(MainPanel, "debug");else JOptionPane.showMessageDialog(null, "Permissão negada");
    }//GEN-LAST:event_debugActionPerformed

    private void sqlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqlActionPerformed
        if(funcionario[0] > 2)c.show(MainPanel, "sql");else JOptionPane.showMessageDialog(null, "Permissão negada");
    }//GEN-LAST:event_sqlActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JMenu avançado;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JMenuItem debug;
    private javax.swing.JMenu estoque;
    private javax.swing.JMenuItem fornecedor;
    private javax.swing.JMenuItem forprod;
    private javax.swing.JMenuItem funcionari;
    private javax.swing.JMenu home;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem produto;
    private javax.swing.JMenuItem sql;
    private javax.swing.JMenuItem venda;
    private javax.swing.JMenu visualizar;
    // End of variables declaration//GEN-END:variables

}
