/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Communication.DataManager;
import static Communication.Engine.ColorToTable;
import static Communication.Engine.GetMarcaModelo;
import static Communication.Engine.GetRowSize;
import static Communication.Engine.GetSingleData;
import static Communication.Engine.MarcaModeloCBox;
import static Communication.Engine.RowToComboBox;
import static Communication.Engine.isNumeric;
import Communication.LabelTimer;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LeoFuking
 */
public class Produto extends javax.swing.JPanel {

    private boolean echo = false;
    
    private int Marca = 0;
    private int Modelo = 0;
    
    public Produto() {
        initComponents();
        salvo.setVisible(false);
        modelo.setModel(RowToComboBox("modelo", "nome"));
        pintura.setModel(RowToComboBox("pintura", "nome"));
        marca.setModel(RowToComboBox("marca", "nome"));
        ResetFrame();
    }

    private void ResetFrame(){
        tabela.setModel(ColorToTable(""));
        valor.setText("0.00");
        quantidade.setText("0");
        marca.setSelectedIndex(0);
        modelo.setSelectedIndex(0);
        pintura.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pintura = new javax.swing.JComboBox<>();
        valor = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        limpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        marca = new javax.swing.JComboBox<>();
        modelo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        display = new javax.swing.JPanel();
        salvo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 0, 14))); // NOI18N

        pintura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pintura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pinturaItemStateChanged(evt);
            }
        });

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade");

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        jLabel9.setText("Modelo");

        jLabel10.setText("Pintura");

        cor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                corKeyReleased(evt);
            }
        });

        jLabel11.setText("Valor");

        marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        marca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                marcaItemStateChanged(evt);
            }
        });
        marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                marcaMouseReleased(evt);
            }
        });

        modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        modelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modeloItemStateChanged(evt);
            }
        });
        modelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                modeloMouseReleased(evt);
            }
        });

        jLabel12.setText("Marca");

        jLabel1.setText("Cor");

        display.setBackground(new java.awt.Color(255, 255, 255));
        display.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        display.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        salvo.setForeground(new java.awt.Color(51, 204, 0));
        salvo.setText("Salvo com sucesso!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(19, 19, 19)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pintura, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pintura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar)
                            .addComponent(limpar)
                            .addComponent(salvo)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pinturaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pinturaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_pinturaItemStateChanged

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        if(String.valueOf(marca.getSelectedItem()) == ""){JOptionPane.showMessageDialog(null,"Selecione uma marca");}
        else{
            if(String.valueOf(modelo.getSelectedItem()) == ""){JOptionPane.showMessageDialog(null,"Selecione um modelo");}
            else{
                if(String.valueOf(pintura.getSelectedItem()) == ""){JOptionPane.showMessageDialog(null,"Selecione uma pintura");}
                else{
                    if(!isNumeric(valor.getText())){JOptionPane.showMessageDialog(null,"Digite um valor válido para valor");}
                    else{
                        if(!isNumeric(quantidade.getText())){JOptionPane.showMessageDialog(null,"Digite um valor válido para quantidade");}
                        else{
                            if(tabela.getSelectedRow() == -1){JOptionPane.showMessageDialog(null,"Selecione uma linha na tabela para salvar");}
                            else{
                                if(tabela.getValueAt(tabela.getSelectedRow(),0) == null){JOptionPane.showMessageDialog(null,"Selecione uma linha válida");}
                                else{
                                    String[] save = new String[6];
                                    save[0] = String.valueOf((int) GetSingleData("SELECT marca_id FROM marca WHERE nome LIKE '"+marca.getSelectedItem()+"'","marca_id"));
                                    save[1] = String.valueOf((int) GetSingleData("SELECT modelo_id FROM modelo WHERE nome LIKE '"+modelo.getSelectedItem()+"'","modelo_id"));
                                    save[2] = String.valueOf((int) GetSingleData("SELECT cor_id FROM cor WHERE nome LIKE '"+(String) tabela.getValueAt(tabela.getSelectedRow(),0)+"'","cor_id"));
                                    save[3] = String.valueOf((int) GetSingleData("SELECT pintura_id FROM pintura WHERE nome LIKE '"+pintura.getSelectedItem()+"'","pintura_id"));
                                    save[4] = valor.getText();
                                    save[5] = quantidade.getText();
                                    int s1 = GetRowSize("produto");
                                    DataManager.CadastrarProduto(save);
                                    int s2 = GetRowSize("produto");
                                    if(s2 > s1){salvo.setVisible(true);new LabelTimer(2,salvo);}
                                    ResetFrame();
                                }}}}}}}
    }//GEN-LAST:event_salvarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void corKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corKeyReleased
        tabela.setModel(ColorToTable(cor.getText()));
    }//GEN-LAST:event_corKeyReleased

    private void marcaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_marcaItemStateChanged
        if(echo) echo = false;
        else{
            echo = true;
            if(marca.getSelectedItem() == ""){
                modelo.setModel(RowToComboBox("modelo", "nome"));
            }else{
                Marca = (int) GetSingleData("SELECT marca_id FROM marca WHERE nome LIKE '"+marca.getSelectedItem()+"'","marca_id");
                modelo.setModel(MarcaModeloCBox(true,String.valueOf(Marca)));
            }
        }
    }//GEN-LAST:event_marcaItemStateChanged

    private void marcaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaMouseReleased
        echo = false;
    }//GEN-LAST:event_marcaMouseReleased

    private void modeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modeloItemStateChanged
    if(echo) echo = false;
    else{
        echo = true;
        if(modelo.getSelectedItem() == ""){
            marca.setModel(RowToComboBox("marca", "nome"));
        }else{
            Modelo = (int) GetSingleData("SELECT modelo_id FROM modelo WHERE nome LIKE '"+modelo.getSelectedItem()+"'","modelo_id");
            String buffer = String.valueOf(modelo.getSelectedItem());
            String[] s = new String[1];
            s = GetMarcaModelo(false,String.valueOf(modelo.getSelectedItem()));
            marca.setSelectedItem(s[0]);
            modelo.setSelectedItem(buffer);
        }
    }
    }//GEN-LAST:event_modeloItemStateChanged

    private void modeloMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeloMouseReleased
        echo = false;
    }//GEN-LAST:event_modeloMouseReleased

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        ResetFrame();
    }//GEN-LAST:event_limparActionPerformed

    private void tabelaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseReleased
        if(tabela.getSelectedRow() != -1){
        if(tabela.getSelectedRowCount() > 1){
            int[] i = tabela.getSelectedRows();
            tabela.setRowSelectionInterval(i[0],i[0]);
        }
        if(tabela.getSelectedRow() < tabela.getRowCount()){
        display.setBackground(Color.decode((String)tabela.getValueAt(tabela.getSelectedRow(),1)));
        }
        }
    }//GEN-LAST:event_tabelaMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cor;
    private javax.swing.JPanel display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpar;
    private javax.swing.JComboBox<String> marca;
    private javax.swing.JComboBox<String> modelo;
    private javax.swing.JComboBox<String> pintura;
    private javax.swing.JTextField quantidade;
    private javax.swing.JButton salvar;
    private javax.swing.JLabel salvo;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
