/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Communication.DataManager;
import static Communication.DataManager.RemoveById;
import static Communication.Engine.ColumnNamesCBox;
import static Communication.Engine.GetSingleData;
import static Communication.Engine.SetFilterTableModel;
import static Communication.Engine.SetTableModel;
import static Communication.Engine.TabelasCBox;
import javax.swing.JOptionPane;

/**
 *
 * @author LeoFuking
 */
public class Visualizar extends javax.swing.JPanel {

    /**
     * Creates new form Visualizar
     */
    public Visualizar() {
        initComponents();
        entidade.setModel(TabelasCBox());
        tabela.setModel(new javax.swing.table.DefaultTableModel(new String[][]{{""}},new String[]{" "}));
        campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        entidade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        remover = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campo = new javax.swing.JComboBox<>();
        filtro = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visualizar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Copperplate Gothic Light", 0, 14))); // NOI18N

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        entidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        entidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                entidadeItemStateChanged(evt);
            }
        });

        jLabel1.setText("Entidade");

        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtrar");

        campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        campo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campoItemStateChanged(evt);
            }
        });

        filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filtroKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remover, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(remover)
                        .addComponent(entidade, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(filtro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_entidadeItemStateChanged
        if(entidade.getSelectedIndex() == 0){
            tabela.setModel(new javax.swing.table.DefaultTableModel(new String[][]{{""}},new String[]{" "}));
            campo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{""}));
        }
        else{
            tabela.setModel(SetTableModel((String)entidade.getSelectedItem()));
            campo.setModel(ColumnNamesCBox((String)entidade.getSelectedItem()));
        }
    }//GEN-LAST:event_entidadeItemStateChanged

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        if(tabela.getSelectedRowCount() == 0){JOptionPane.showMessageDialog(null,"Selecione no mínimo uma linha na tabela para salvar");}
        else{
            int[] Rows = tabela.getSelectedRows();
            for(int i = 0; i < Rows.length; i++){
                if(tabela.getValueAt(Rows[i],0) == null){JOptionPane.showMessageDialog(null,"Item na linha "+(Rows[i]+1)+" é inválido");i = Rows.length;}
                else{
                    RemoveById((String)entidade.getSelectedItem(),String.valueOf(tabela.getValueAt(Rows[i],0)));
                }
            }
        }
    }//GEN-LAST:event_removerActionPerformed

    private void campoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campoItemStateChanged

    }//GEN-LAST:event_campoItemStateChanged

    private void filtroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtroKeyReleased
        if(campo.getSelectedIndex() != 0){
            tabela.setModel(SetFilterTableModel((String) entidade.getSelectedItem(),new String[]{(String)campo.getSelectedItem(),filtro.getText()}));
        }
    }//GEN-LAST:event_filtroKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> campo;
    private javax.swing.JComboBox<String> entidade;
    private javax.swing.JTextField filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton remover;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
